#
# Generated source file. DO NOT CHANGE!

from .constants import *
from .vadere_vars import *

# Command constants for VaderePersonAPI
CMD_GET_V_PERSON_VARIABLE = 0xAE
RESPONSE_GET_V_PERSON_VARIABLE = 0xBE
CMD_SET_V_PERSON_VARIABLE = 0xCE
CMD_SUBSCRIBE_V_PERSON_VARIABLE = 0xDE
RESPONSE_SUBSCRIBE_V_PERSON_VARIABLE = 0xEE
CMD_SUBSCRIBE_V_PERSON_CONTEXT = 0x8E
RESPONSE_SUBSCRIBE_V_PERSON_CONTEXT = 0x9E

# Command constants for VadereMiscAPI
CMD_GET_V_MISC_VARIABLE = 0xAC
RESPONSE_GET_V_MISC_VARIABLE = 0xBC
CMD_SET_V_MISC_VARIABLE = 0xCC
CMD_SUBSCRIBE_V_MISC_VARIABLE = 0xDC
RESPONSE_SUBSCRIBE_V_MISC_VARIABLE = 0xEC
CMD_SUBSCRIBE_V_MISC_CONTEXT = 0x8C
RESPONSE_SUBSCRIBE_V_MISC_CONTEXT = 0x9C

# Command constants for VadereSimulationAPI
CMD_GET_V_SIM_VARIABLE = 0xAB
RESPONSE_GET_V_SIM_VARIABLE = 0xBB
CMD_SET_V_SIM_VARIABLE = 0xcb
CMD_SUBSCRIBE_V_SIM_VARIABLE = 0xDB
RESPONSE_SUBSCRIBE_V_SIM_VARIABLE = 0xEB
CMD_SUBSCRIBE_V_SIM_CONTEXT = 0x8B
RESPONSE_SUBSCRIBE_V_SIM_CONTEXT = 0x9B
CMD_PAYLOAD_RESPONSE = 0x7B

# Command constants for VaderePolygonAPI
CMD_GET_V_POLYGON_VARIABLE = 0xA8
RESPONSE_GET_V_POLYGON_VARIABLE = 0xB8
CMD_SET_V_POLYGON_VARIABLE = 0xC8
CMD_SUBSCRIBE_V_POLYGON_VARIABLE = 0xD8
RESPONSE_SUBSCRIBE_V_POLYGON_VARIABLE = 0xE8
CMD_SUBSCRIBE_V_POLYGON_CONTEXT = 0x88
RESPONSE_SUBSCRIBE_V_POLYGON_CONTEXT = 0x98
