#
# Generated source file. DO NOT CHANGE!

from . constants import *
from . vadere_vars import *

# Command constants for VaderePersonAPI
CMD_GET_V_PERSON_VARIABLE = 0xae
RESPONSE_GET_V_PERSON_VARIABLE = 0xbe
CMD_SET_V_PERSON_VARIABLE = 0xce
CMD_SUBSCRIBE_V_PERSON_VARIABLE = 0xde
RESPONSE_SUBSCRIBE_V_PERSON_VARIABLE = 0xee
CMD_SUBSCRIBE_V_PERSON_CONTEXT = 0x8e
RESPONSE_SUBSCRIBE_V_PERSON_CONTEXT = 0x9e

# Command constants for VadereMiscAPI
CMD_GET_V_MISC_VARIABLE = 0xac
RESPONSE_GET_V_MISC_VARIABLE = 0xbc
CMD_SET_V_MISC_VARIABLE = 0xcc
CMD_SUBSCRIBE_V_MISC_VARIABLE = 0xdc
RESPONSE_SUBSCRIBE_V_MISC_VARIABLE = 0xec
CMD_SUBSCRIBE_V_MISC_CONTEXT = 0x8c
RESPONSE_SUBSCRIBE_V_MISC_CONTEXT = 0x9c

# Command constants for VadereSimulationAPI
CMD_GET_V_SIM_VARIABLE = 0xab
RESPONSE_GET_V_SIM_VARIABLE = 0xbb
CMD_SET_V_SIM_VARIABLE = 0xcb
CMD_SUBSCRIBE_V_SIM_VARIABLE = 0xdb
RESPONSE_SUBSCRIBE_V_SIM_VARIABLE = 0xeb
CMD_SUBSCRIBE_V_SIM_CONTEXT = 0x8b
RESPONSE_SUBSCRIBE_V_SIM_CONTEXT = 0x9b

# Command constants for VaderePolygonAPI
CMD_GET_V_POLYGON_VARIABLE = 0xa8
RESPONSE_GET_V_POLYGON_VARIABLE = 0xb8
CMD_SET_V_POLYGON_VARIABLE = 0xc8
CMD_SUBSCRIBE_V_POLYGON_VARIABLE = 0xd8
RESPONSE_SUBSCRIBE_V_POLYGON_VARIABLE = 0xe8
CMD_SUBSCRIBE_V_POLYGON_CONTEXT = 0x88
RESPONSE_SUBSCRIBE_V_POLYGON_CONTEXT = 0x98

