from . import constants as tc


# control commands
# todo move to correct files
CMD_CONTROLLER = 0x0d
RESPONSE_CMD_CONTROLLER = 0x1d
VAR_REDIRECT = 0xff
VAR_INIT = 0x00
CMD_FILE_SEND = 0x75
#  command: simulation state
CMD_SIMSTATE = 0x04


# rename variable to match vadere versions
VAR_ID_LIST = tc.TRACI_ID_LIST
VAR_COUNT = tc.ID_COUNT
VAR_ADD = tc.ADD
VAR_POSITION_CONVERSION = tc.POSITION_CONVERSION

# New Vadere only commands and variables

# VaderePersonApi
VAR_HAS_NEXT_TARGET = 0x03
VAR_NEXT_TARGET_LIST_INDEX = 0x04
VAR_VELOCITY = 0x41
VAR_INFORMATION_ITEM = 0xfd
VAR_TARGET_LIST = 0xfe
VAR_POSITION_LIST = 0xff
VAR_NEXT_ID = 0x02

# VaderePolygon
VAR_TOPOGRAPHY_BOUNDS = 0x02
VAR_CENTROID = 0x50

# VadereSimulationAPI
VAR_SIM_CONFIG = 0x7e
VAR_CACHE_HASH = 0x7d
VAR_DEPARTED_PEDESTRIAN_IDS = 0x74
VAR_ARRIVED_PEDESTRIAN_PEDESTRIAN_IDS = 0x7a
VAR_COORD_REF = 0x90

# VadereMiscAPI
VAR_ADD_TARGET_CHANGER = 0x00
VAR_REMOVE_TARGET_CHANGER = 0x01
VAR_ADD_STIMULUS_INFOS = 0x02
VAR_GET_ALL_STIMULUS_INFOS = 0x03
